name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: >-
          --privileged
          --network host

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t transformer-image .

  train:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job completes before running this job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run training script
        run: |
          docker run --rm transformer-image python src/train.py

  translate:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job completes before running this job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run translation script
        run: |
          docker run --rm transformer-image python src/translate.py